### ISSUE TITLE
TMC2209 UART?

### ISSUE THREAD

**Issue by Miraculix200** [le3tspeak/Marlin-2.0.X-Sapphire-PRO#1]
So, how does the TMC2209 UART connection look like on the hardware side?

You connect RX/TX on the 2209 together, and then connect them to a dedicated pin for each stepper driver on the board, right? Did you change the hardware address of the stepper drivers? Did you use a resistance between RX/TX and the pin on the board? Did you cut the RX/TX pins on the bottom side of the stepper module (because according to the schematic of the Robin Nano 1.2 board, the RX pin is connected to the CLK pin via the board).

Also, what needs to be done on the software side? Simply set the drivers to TMC2209 (instead of TMC2209_STANDALONE) and uncomment the lines in pins_MKS_ROBIN_NANO.h? Or is there somethign else to be done?

Tags for search engines: TMC2209 Sapphire Pro UART MKS Robin Nano

**Comment by Miraculix200** [comment]
I think I just screwed up because I did cut the RX/TX pins on the bottom side. Getting TMC CONNECTION ERROR on the display. Will be fun to put this thing together again

**Comment by le3tspeak** [comment]
Q: You connect RX/TX on the 2209 together, and then connect them to a dedicated pin for each stepper driver on the board, right? 


A: Yes PA3 ->X, PA6->Y, PA1->Z

Q:Did you change the hardware address of the stepper drivers? 
A: No Default

Q:Did you use a resistance between RX/TX and the pin on the board? 
A: No, One Single Wire

Q: Did you cut the RX/TX pins on the bottom side of the stepper module (because according to the schematic of the Robin Nano 1.2 board, the RX pin is connected to the CLK pin via the board).

A: No, Only Remove All Jumpers for the Driver

Q:Also, what needs to be done on the software side? Simply set the drivers to TMC2209 (instead of TMC2209_STANDALONE) and uncomment the lines in pins_MKS_ROBIN_NANO.h? Or is there somethign else to be done?

A: Yes and TMC Baudrate

**Comment by Miraculix200** [comment]
Thanks. Will try again with the jumpers removed. But I still think I screwed it up haha

**Comment by Miraculix200** [comment]
Actually it looks like it worked. Even with the pins on the bottom side removed. "M122 V" only says "Recv: Testing E connection... OK", but I guess that's normal. Or should it be more verbose?

**Comment by le3tspeak** [comment]
Enable #define TMC_DEBUG for More Informations an Retry M122

**Comment by Miraculix200** [comment]
Will do. Did you also try if it works with the PA9 and PA10 pins from the wifi module slot? Because some people don't want to use the pins on the 5th stepper slot.

**Comment by le3tspeak** [comment]
PA2, PA9, PA10, PB2, PE6 will Work

**Comment by EPDCenter** [comment]
Gracias por responder, qué puente debo eliminar del controlador?https://es.aliexpress.com/item/33028054001.html?spm=a2g0s.9042311.0.0.347a63c0JnZiGQ

**Comment by EPDCenter** [comment]
How would the jumpers go if they did it using slave_addrees?

  /**
   * Four TMC2209 drivers can use the same HW/SW serial port with hardware configured addresses.
   * Set the address using jumpers on pins MS1 and MS2.
   * Address | MS1  | MS2
   *       0 | LOW  | LOW
   *       1 | HIGH | LOW
   *       2 | LOW  | HIGH
   *       3 | HIGH | HIGH

**Comment by le3tspeak** [comment]
FYSTEC V3 is not designed for 1 cable connection 2 cables per driver FYSTEC V2.1 is therefore not feasible for 1 cable connection for all stepper drivers because there are not enough pins available

**Comment by EPDCenter** [comment]
> FYSETC V3 no está diseñado para 1 conexión de cable 2 cables por controlador FYSTEC V2.1, por lo tanto, no es factible para 1 conexión de cable para todos los controladores paso a paso porque no hay suficientes pines disponibles

How could I do it using Slave address? How would the jumpers be placed? : S

**Comment by le3tspeak** [comment]
Meintest du: Ich weiß nicht was du mit dem Serail machen möchtest ab das Robin geht nicht mit HW Serial für UART nur Software Serial und da sind die Jumper nicht nötig da alles Per Firmware eingestellt wird
193/5000
I do not know what you want to do with the serial from the Robin does not work with HW Serial for UART only software serial and there are no jumpers because everything is set by firmware

**Comment by EPDCenter** [comment]
Check it please : https://www.youtube.com/watch?reload=9&v=ZK9ttGcpiC4

**Comment by le3tspeak** [comment]
YES as I said before he also uses software serial and no HW serial everything is set in the FW and not by jumper and a 2 cable connection is required without resistance and he uses PA6 for TX and PA1 for RX an X to 0 Y on 1 on 2 and E on 3

**Comment by EPDCenter** [comment]
How are such ports selected?
